name: publish
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        pip install --upgrade build twine
        python -m build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.10.2
      with:
        password: ${{ secrets.PYPI_TOKEN }}
